import type { BatchSummary } from '../types'
import { Icon } from './Icon'

export function PublishSummary({ summary, onExport, onReview }: { summary: BatchSummary; onExport: (path: string, filename: string) => void; onReview: () => void }) {
  const total = Math.max(summary.total_records, 1)
  return <section className="overflow-hidden rounded-xl border border-[#e3e3e5] bg-white">
    <div className="grid md:grid-cols-2"><div className="border-b border-[#ececee] p-7 md:border-b-0 md:border-r"><p className="text-sm font-medium text-[#777]">Ready to publish</p><p className="mt-2 text-5xl font-semibold tracking-[-0.04em]">{summary.publishable_count}</p><p className="mt-2 text-sm text-[#777]">of {summary.total_records} records meet the export policy</p></div><div className="p-7"><p className="text-sm font-medium text-[#777]">Excluded</p><p className="mt-2 text-5xl font-semibold tracking-[-0.04em] text-[#777]">{summary.attention_count}</p><p className="mt-2 text-sm text-[#777]">records still require a decision or correction</p></div></div>
    <div className="border-t border-[#ececee] px-7 py-6"><div className="flex h-3 overflow-hidden rounded-full bg-[#eeeeef]"><div className="bg-emerald-500" style={{ width: `${summary.publishable_count / total * 100}%` }} /><div className="bg-amber-400" style={{ width: `${summary.needs_review_count / total * 100}%` }} /><div className="bg-indigo-400" style={{ width: `${summary.duplicate_count / total * 100}%` }} /><div className="bg-red-400" style={{ width: `${summary.invalid_count / total * 100}%` }} /></div><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[#777]"><Key color="bg-emerald-500" label="Publishable" value={summary.publishable_count} /><Key color="bg-amber-400" label="Needs Review" value={summary.needs_review_count} /><Key color="bg-indigo-400" label="Duplicate" value={summary.duplicate_count} /><Key color="bg-red-400" label="Invalid" value={summary.invalid_count} /></div></div>
    <div className="flex flex-col gap-3 border-t border-[#ececee] bg-[#fafafa] px-7 py-5 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-xl text-sm leading-6 text-[#666]">The clean export contains canonical fields only and includes trusted automation plus explicitly resolved human decisions.</p><div className="flex shrink-0 gap-2"><button onClick={onReview} className="action-secondary">Review excluded</button><button disabled={!summary.publishable_count} onClick={() => onExport('/export/cleaned-catalog', 'cleaned-catalog.csv')} className="action-primary"><Icon name="download" className="h-4 w-4" />Export clean catalog</button></div></div>
  </section>
}

function Key({ color, label, value }: { color: string; label: string; value: number }) { return <span className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${color}`} />{label} <strong className="text-[#444]">{value}</strong></span> }
