import { useMemo, useState } from 'react'
import type { BatchSummary, Mapping } from '../types'
import { Icon } from './Icon'

export function SchemaMappingTable({ summary, compact = false }: { summary: BatchSummary; compact?: boolean }) {
  const [selected, setSelected] = useState<Mapping | null>(null)
  const profile = useMemo(() => summary.schema_report.profiles.find((item) => item.source_name === selected?.source_field), [selected, summary])
  return <>
    <section className="overflow-hidden rounded-xl border border-[#e3e3e5] bg-white">
      <div className="grid min-w-[720px] grid-cols-[1.2fr_44px_1.2fr_110px_120px_100px] border-b border-[#ececee] bg-[#fafafa] px-5 py-3 text-xs font-medium text-[#777]"><span>Source field</span><span /><span>Canonical field</span><span>Confidence</span><span>Method</span><span>Status</span></div>
      <div className={compact ? 'max-h-[320px] overflow-y-auto' : ''}>{summary.mappings.map((mapping) => <button key={mapping.source_field} onClick={() => setSelected(mapping)} className="grid h-14 w-full min-w-[720px] grid-cols-[1.2fr_44px_1.2fr_110px_120px_100px] items-center border-b border-[#eeeeef] px-5 text-left text-sm transition last:border-0 hover:bg-[#fafafa]"><span className="truncate font-mono text-[13px] text-[#333]">{mapping.source_field}</span><span className="text-[#aaa]">→</span><span className={mapping.canonical_field ? 'truncate font-mono text-[13px] font-medium text-[#222]' : 'text-red-600'}>{mapping.canonical_field ?? 'Unresolved'}</span><span className="font-medium">{mapping.canonical_field ? `${Math.round(mapping.confidence * 100)}%` : '—'}</span><span className="capitalize text-[#777]">{mapping.method.replace(/_/g, ' ')}</span><span><span className={`rounded-full px-2.5 py-1 text-[11px] font-medium ${mapping.auto_applied ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-800'}`}>{mapping.auto_applied ? 'Applied' : 'Review'}</span></span></button>)}</div>
    </section>
    {!compact && selected ? <div className="fixed inset-0 z-[70]" role="dialog" aria-modal="true" aria-label="Mapping details"><button onClick={() => setSelected(null)} className="absolute inset-0 bg-black/20 backdrop-blur-[1px]" aria-label="Close mapping details" /><aside className="absolute inset-y-0 right-0 w-full max-w-[460px] overflow-y-auto border-l border-[#dedee1] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs text-[#888]">Field mapping</p><h2 className="mt-1 font-mono text-xl font-semibold">{selected.source_field}</h2></div><button onClick={() => setSelected(null)} className="grid h-8 w-8 place-items-center rounded-lg text-[#777] hover:bg-[#f2f2f3]" aria-label="Close"><Icon name="x" className="h-4 w-4" /></button></div><div className="mt-6 rounded-xl border border-[#e5e5e7] p-4"><p className="text-xs text-[#888]">Canonical destination</p><div className="mt-2 flex items-center gap-3"><span className="font-mono text-sm">{selected.source_field}</span><span className="text-[#aaa]">→</span><span className="font-mono text-sm font-semibold">{selected.canonical_field ?? 'Unresolved'}</span></div></div><dl className="mt-6 grid grid-cols-2 gap-4"><Fact label="Inferred type" value={profile?.inferred_type ?? 'Not available'} /><Fact label="Confidence" value={`${Math.round(selected.confidence * 100)}%`} /><Fact label="Null values" value={profile ? `${profile.null_percentage.toFixed(1)}%` : '—'} /><Fact label="Unique values" value={profile ? `${profile.unique_percentage.toFixed(1)}%` : '—'} /><Fact label="Validity" value={profile?.validity_rate != null ? `${(profile.validity_rate * 100).toFixed(1)}%` : 'Not measured'} /><Fact label="Method" value={selected.method.replace(/_/g, ' ')} /></dl>{profile?.sample_values?.length ? <section className="mt-7"><h3 className="section-label">Observed samples</h3><div className="mt-3 flex flex-wrap gap-2">{profile.sample_values.map((sample) => <code key={sample} className="rounded-md bg-[#f3f3f4] px-2.5 py-1.5 text-xs">{sample}</code>)}</div></section> : null}</aside></div> : null}
  </>
}

function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-[#888]">{label}</dt><dd className="mt-1 text-sm font-medium capitalize">{value}</dd></div> }
