import type { BatchSummary, ProcessingRun, RecordItem, ViewId } from '../types'
import { Icon } from '../components/Icon'
import { PipelineRail } from '../components/PipelineRail'
import { RecordStatus, StatusBadge } from '../components/StatusBadge'

export function OverviewView({ summary, records, run, onNavigate, onRefreshRun }: { summary: BatchSummary; records: RecordItem[]; run: ProcessingRun | null; onNavigate: (view: ViewId) => void; onRefreshRun: () => void }) {
  const total = Math.max(summary.total_records, 1)
  return <div className="space-y-7">
    <header><h1 className="text-[32px] font-semibold tracking-[-0.03em]">CatalogFlow</h1><p className="mt-1.5 text-[15px] text-[#6b6b6b]">Turn messy merchant feeds into clean, trusted catalog data.</p></header>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]">
      <section className="rounded-xl border border-[#e3e3e5] bg-white p-6"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-[#777]">Current batch</p><h2 className="mt-2 text-xl font-semibold tracking-[-0.015em]">{summary.filename}</h2><p className="mt-1 font-mono text-xs text-[#929292]">CF-{String(summary.batch_id).padStart(4, '0')} · uploaded {new Date(summary.uploaded_at).toLocaleString()}</p></div><StatusBadge status={summary.processing_status ?? summary.status} /></div><div className="mt-7 flex flex-wrap gap-x-10 gap-y-4"><InlineMetric value={summary.total_records} label="records" /><InlineMetric value={summary.publishable_count} label="publishable" tone="green" /><InlineMetric value={summary.attention_count} label="need attention" tone="amber" /><InlineMetric value={`${summary.average_confidence.toFixed(1)}%`} label="avg confidence" /></div><div className="mt-7 flex flex-wrap items-center gap-4 border-t border-[#eeeeef] pt-4 text-xs text-[#777]"><span>{run?.processor_type === 'databricks' ? 'Databricks' : 'Local'} processor</span><span className="h-1 w-1 rounded-full bg-[#ccc]" /><span>{run?.raw_uri?.startsWith('s3://') ? 'S3' : 'Local'} storage</span>{summary.processor_type === 'databricks' ? <button onClick={onRefreshRun} className="ml-auto inline-flex items-center gap-1.5 text-blue-600 hover:underline"><Icon name="refresh" className="h-3.5 w-3.5" />Refresh status</button> : null}</div></section>
      <section className="rounded-xl border border-[#e3e3e5] bg-white p-6"><div className="flex items-baseline justify-between"><div><p className="text-sm font-medium text-[#777]">Needs attention</p><p className="mt-2 text-3xl font-semibold tracking-[-0.03em]">{summary.attention_count} <span className="text-base font-normal text-[#888]">records</span></p></div><button onClick={() => onNavigate('review')} className="text-sm font-medium text-blue-600 hover:underline">Review all</button></div><div className="mt-5 divide-y divide-[#eeeeef]"><AttentionRow label="Needs Review" value={summary.needs_review_count} tone="amber" /><AttentionRow label="Duplicate" value={summary.duplicate_count} tone="blue" /><AttentionRow label="Invalid" value={summary.invalid_count} tone="red" /></div></section>
    </div>

    <section><div className="mb-3"><h2 className="text-lg font-semibold">Processing pipeline</h2><p className="mt-1 text-sm text-[#777]">How the current feed moved from source to publishable catalog.</p></div><PipelineRail summary={summary} onNavigate={onNavigate} /></section>

    <section className="rounded-xl border border-[#e3e3e5] bg-white p-6"><div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="text-lg font-semibold">Data quality</h2><p className="mt-1 text-sm text-[#777]">A focused view of quality and publication readiness.</p></div><div className="grid grid-cols-2 gap-x-9 gap-y-4 sm:grid-cols-5"><SmallMetric label="Schema drift" value={`${summary.schema_drift_count} fields`} /><SmallMetric label="Avg confidence" value={`${summary.average_confidence.toFixed(1)}%`} /><SmallMetric label="Publishable" value={`${Math.round(summary.publishable_count / total * 100)}%`} /><SmallMetric label="Duplicates" value={summary.duplicate_count} /><SmallMetric label="Invalid" value={summary.invalid_count} /></div></div><div className="mt-6 flex h-3 overflow-hidden rounded-full bg-[#eeeeef]" aria-label="Catalog quality distribution"><div className="bg-emerald-500" style={{ width: `${summary.publishable_count / total * 100}%` }} /><div className="bg-amber-400" style={{ width: `${summary.needs_review_count / total * 100}%` }} /><div className="bg-indigo-400" style={{ width: `${summary.duplicate_count / total * 100}%` }} /><div className="bg-red-400" style={{ width: `${summary.invalid_count / total * 100}%` }} /></div><div className="mt-3 flex flex-wrap gap-5 text-xs text-[#777]"><Legend color="bg-emerald-500" label="Publishable" /><Legend color="bg-amber-400" label="Needs Review" /><Legend color="bg-indigo-400" label="Duplicate" /><Legend color="bg-red-400" label="Invalid" /></div></section>

    <section className="overflow-hidden rounded-xl border border-[#e3e3e5] bg-white"><div className="flex items-center justify-between border-b border-[#ececee] px-5 py-4"><div><h2 className="text-lg font-semibold">Recent records</h2><p className="mt-0.5 text-sm text-[#888]">A preview of the latest processed catalog.</p></div><button onClick={() => onNavigate('records')} className="text-sm font-medium text-blue-600 hover:underline">View all records →</button></div><table className="w-full text-left text-sm"><thead className="bg-[#fafafa] text-xs font-medium text-[#777]"><tr><th className="px-5 py-3">Product</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Status</th><th className="px-5 py-3">Issue</th></tr></thead><tbody className="divide-y divide-[#eeeeef]">{records.slice(0, 6).map((record) => <tr key={record.id} className="hover:bg-[#fafafa]"><td className="px-5 py-3.5"><p className="font-medium">{record.cleaned_product_name}</p><p className="mt-0.5 font-mono text-xs text-[#999]">{record.sku ?? 'NO-SKU'}</p></td><td className="px-4 py-3.5 text-[#666]">{record.cleaned_category ?? '—'}</td><td className="px-4 py-3.5 font-medium">{record.confidence_score.toFixed(0)}%</td><td className="px-4 py-3.5"><RecordStatus record={record} /></td><td className="max-w-[250px] truncate px-5 py-3.5 text-[#777]">{record.issue_reasons[0] ?? '—'}</td></tr>)}</tbody></table></section>
  </div>
}

function InlineMetric({ value, label, tone }: { value: number | string; label: string; tone?: 'green' | 'amber' }) { return <div><p className={`text-2xl font-semibold tracking-[-0.02em] ${tone === 'green' ? 'text-emerald-700' : tone === 'amber' ? 'text-amber-700' : ''}`}>{value}</p><p className="mt-1 text-xs text-[#888]">{label}</p></div> }
function AttentionRow({ label, value, tone }: { label: string; value: number; tone: 'amber' | 'blue' | 'red' }) { const cls = tone === 'amber' ? 'bg-amber-50 text-amber-800' : tone === 'blue' ? 'bg-indigo-50 text-indigo-700' : 'bg-red-50 text-red-700'; return <div className="flex items-center justify-between py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${cls}`}>{label}</span><span className="text-sm font-semibold">{value}</span></div> }
function SmallMetric({ label, value }: { label: string; value: string | number }) { return <div><p className="text-xs text-[#8a8a8a]">{label}</p><p className="mt-1 text-base font-semibold">{value}</p></div> }
function Legend({ color, label }: { color: string; label: string }) { return <span className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${color}`} />{label}</span> }
